[package]
name = "pqc"
version = "0.1.0"
authors = ["Jake Probst <jake.probst@gmail.com>"]

[dependencies]
byteorder = "0.5.1"

[lib]
name = "pqc"
path = "src/lib.rs"

[[bin]]
name = "pqc"
path = "src/main.rs"
